'use strict';
const $=s=>document.querySelector(s);let view='library',resultId=null,next=null,evidence=[],generation=0;
const el=(tag,text,cls)=>{const x=document.createElement(tag);if(text!=null)x.textContent=text;if(cls)x.className=cls;return x;};
async function api(operation,args={}){const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation,args})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function message(t){$('#message').textContent=t;}
function action(parent,label,fn){const b=el('button',label);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){message(e.message);}finally{b.disabled=false;}};parent.append(b);}
function link(parent,url){try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))return;const a=el('a','Open source');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';parent.append(a);}catch{}}
function render(rows){for(const row of rows){const card=el('article');if(view==='library'){
 card.append(el('h3',row.author?`@${row.author}`:'Saved post'),el('p',row.text||'Attachment without captured post text'));link(card,row.url);
 for(const p of row.supporting_passages||[]){card.append(el('p',p.coverage||p.role,'meta'),el('blockquote',p.quote));}
 const actions=el('div',null,'actions');action(actions,'Cite in note',()=>{evidence=(row.supporting_passages||[]).slice(0,3).map(p=>({observation_id:p.observation_id,field:p.field||'text',start:p.start,end:p.end,quote:p.quote}));$('#citation').textContent=`${evidence.length} exact source spans attached.`;$('#note').focus();});
 action(actions,'Request media review',async()=>{const objective=prompt('What should the media review help you understand?');if(!objective)return;const source=(row.supporting_passages||[]).find(p=>p.role!=='post');await api('request_media',{observation_id:source?.observation_id||row.observation_id,objective});message('Media review queued. An agent can inspect the source and complete it.');});card.append(actions);
 }else if(view==='research'){
 card.append(el('h3',row.name),el('p',`${row.kind} · version ${row.version} · ${row.objective}`,'meta'));
 if(row.changed_evidence?.length)card.append(el('p','Review needed: a cited source has a newer captured version.'));
 else if(row.newer_corpus_available)card.append(el('p','Newer library material is available; this does not invalidate the note.','meta'));
 card.append(el('pre',typeof row.content==='string'?row.content:JSON.stringify(row.content,null,2)));
 }else{
 card.append(el('h3',row.objective),el('p',row.state,'meta'));
 action(card,'Inspect source',async()=>{const [s]=await api('get',{observation_ids:[row.observation_id]});if(['image/png','image/jpeg','image/webp','image/gif'].includes(s.raw.mime)){const image=el('img');image.src='/media/'+row.observation_id;image.alt='Cached source image for review';card.append(image);}card.append(el('pre',JSON.stringify(s.raw,null,2)));link(card,s.raw.url);});
 if(row.state==='pending'){const area=el('textarea');area.placeholder='Paste an inspected visual analysis or transcript (timecodes are preserved).';area.setAttribute('aria-label','Media analysis');const kind=el('select');for(const value of ['visual','transcript']){const o=el('option',value);o.value=value;kind.append(o);}card.append(area,kind);action(card,'Save analysis',async()=>{await api('complete_media',{request_id:row.id,description:area.value,kind:kind.value,expected_version:row.version});message('Analysis saved. Keyword search includes it now; rebuild the meaning index to include it there.');await load();});}
 }$('#results').append(card);}}
async function page(append=false){const current=resultId,currentView=view;const d=await api('result',{result_id:resultId,offset:append?next:0,limit:20});if(current!==resultId||currentView!==view)return;if(!append)$('#results').replaceChildren();render(d.rows);next=d.next_offset;$('#more').hidden=next==null;}
async function load(){const ticket=++generation;message('Searching…');$('#more').hidden=true;try{let d;if(view==='library')d=await api('search_library',{text:$('#query').value,mode:$('#mode').value});else if(view==='research')d=await api('research_search',{text:$('#query').value});else d=await api('media_requests');if(ticket!==generation)return;resultId=d.receipt.result_id;await page();if(ticket!==generation)return;message(`${d.receipt.count} results.${d.receipt.semantic_index && d.receipt.semantic_index.workspace_revision_now>d.receipt.semantic_index.enrichment_revision?' New evidence is available; rebuild the meaning index to include it.':''}${d.receipt.fallback?' Meaning search unavailable; showing word matches. '+d.receipt.fallback:''}`);}catch(e){message(e.message);}}
$('#search-form').onsubmit=async e=>{e.preventDefault();await load();};$('#more').onclick=()=>page(true).catch(e=>message(e.message));
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{generation++;view=b.dataset.view;$('#query').required=view==='library';$('#mode').hidden=view!=='library';$('#search').hidden=view==='media';$('#results').replaceChildren();$('#more').hidden=true;if(view!=='library'||$('#query').value.trim())load();else message('Search across your saved posts and extracted attachments.');};
$('#note-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const inv=await api('investigate',{objective:$('#title').value});if(evidence.length)await api('claim',{investigation_id:inv.id,name:$('#title').value,statement:$('#note').value,evidence,status:'proposed'});else await api('artifact',{investigation_id:inv.id,name:$('#title').value,kind:'note',content:{text:$('#note').value,status:'unverified'}});$('#note-form').reset();evidence=[];$('#citation').textContent='No citations attached.';message('Note saved to Research.');}catch(err){message(err.message);}finally{b.disabled=false;}};
api('inventory').then(d=>$('#inventory').textContent=`${d.posts.toLocaleString()} saved posts · ${d.sources.likes.toLocaleString()} likes · ${d.sources.bookmarks.toLocaleString()} bookmarks`).catch(e=>message(e.message));
