const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..','extension');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const bundles={
  'page.bundle.js':['core.js','network.js'],
  'collector.bundle.js':['core.js','dom.js','collector.js']
};
for(const [name,files] of Object.entries(bundles)){
  let body='// Generated by node scripts/build.cjs. Edit source files, then rebuild.\n(()=>{\nconst globalThis = {}; const module = undefined;\n';
  for(const file of files){
    body+=`\n// ${file}\n${read(file)}\n`;
    if(file==='core.js')body+='const GoldCore = globalThis.GoldCore;\n';
    if(file==='dom.js')body+='const GoldDOM = globalThis.GoldDOM;\n';
  }
  body+='})();\n';
  if(process.argv.includes('--check')){
    if(!fs.existsSync(path.join(root,name))||read(name)!==body)throw new Error(`${name} is stale. Run npm run build.`);
  }else fs.writeFileSync(path.join(root,name),body);
}
console.log(process.argv.includes('--check')?'Content bundles are current.':'Built two independent content-script bundles.');
